const CarData = [
  {
    id: 1,
    Name: "Audi A1 S-Line",
    price: 245,
    year: 2020,
    Capacity: 5,
    Transmission: "Automatic",
    Fuel: "Petrol",
  },
  {
    id: 2,
    Name: "Volkeswagen Golf",
    price: 200,
    year: 2019,
    Capacity: 5,
    Transmission: "Automatic",
    Fuel: "Petrol",
  },
  {
    id: 3,
    Name: "Bmw 330i",
    price: 300,
    year: 2021,
    Capacity: 5,
    Transmission: "Automatic",
    Fuel: "Hybrid",
  },
  {
    id: 4,
    Name: "Mercedez GLS",
    price:300,
    year: 2022,
    Capacity: 7,
    Transmission: "Automatic",
    Fuel: "Petrol",
  },
  {
    id: 5,
    Name: "VW Passat",
    price: 245,
    year: 2020,
    Capacity: 5,
    Transmission: "Automatic",
    Fuel: "Petrol",
  },
  {
    id: 5,
    Name: "Toyota Carmy",
    price: 245,
    year: 2018,
    Capacity: 5,
    Transmission: "Manual",
    Fuel: "Hybrid",
  },
];
export default CarData;